/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mornning_lunar_KLunar */

#ifndef _Included_com_mornning_lunar_KLunar
#define _Included_com_mornning_lunar_KLunar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mornning_lunar_KLunar
 * Method:    sunToLunar
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mornning_lunar_KLunar_sunToLunar
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
